#!/bin/bash
pkill dwmblock
pkill diodon
pkill "picom --transparent-clipping" # Using This Option here because not working when it is in .config/picom/picom.conf
# Default NightLight
redshift -oP -O 4200


# Setting Amazing Background Wallpaper
feh "$HOME/Pictures/Redmi A3x.png" --bg-center

# Setting Status-Bar's Text to Current Date-time and Setup Brief
# while true
# do
# 	xsetroot -name " $(date) | Linux Mint + DWM " && sleep 1
# done &

# This Should run in background
dwmblocks &

# Amazing Compositor for X11
picom --transparent-clipping  &

# Starting Clipboard Manager ( This Should run in background)
diodon &
